spring:
  main:
    banner-mode: off

topics:
  telebot: ${DATA_TOPIC:demo-topic}

server:
  port: 8082
app:
  kafka:
    consumer:
      bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      auto_offset_reset: earliest
      client_id: ${KAFKA_CLIENT_ID:rehtang-app}


telegram:
  token: "5674163812:AAFPt0F47QD6p2DquIYTufJ4Z3kZX29z-Q0"
  username: "RehtangCryptocurrencyAlertBot"